controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Controllers to load
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:

    # Wheel joints — skid steer: 2 left, 2 right
    left_wheel_names:  ['F_L_W_joint', 'B_L_W_joint']
    right_wheel_names: ['F_R_W_joint', 'B_R_W_joint']

    # Robot geometry
    wheel_separation: 1.07
    wheel_radius: 0.075

    # Odometry
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal:     [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal:    [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # Topics
    cmd_vel_topic: cmd_vel
    odom_topic: odom

    # Velocity limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0       # m/s
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0       # rad/s
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 2.0

    # Publishing
    publish_rate: 50.0
    use_stamped_vel: false
